window.laptopModels = {
    "HP": [
        { name: "HP 14s", image: "images/sell-laptop-models/hp/HP 14s.webp", 
           },
        { name: "HP 15", image: "images/sell-laptop-models/hp/HP 15.webp", 
          },
        { name: "HP 15s", image: "images/sell-laptop-models/hp/hp 15s.webp", 
            },
        { name: "HP ChromeBook", image: "images/sell-laptop-models/hp/HP CHROMEBOOK X360.webp", 
           },
        { name: "HP EliteBook", image: "images/sell-laptop-models/hp/HP ELITEBOOK 820 G4.webp", 
            },
        { name: "HP Envy", image: "images/sell-laptop-models/hp/hp envy x360.webp", 
            },
        { name: "HP 250R G9", image: "images/sell-laptop-models/hp/hp laptop 250R G9.webp", 
            },
        { name: "HP Pavilion", image: "images/sell-laptop-models/hp/HP PAVILION.webp", 
            },
        { name: "HP ProBook", image: "images/sell-laptop-models/hp/HP PROBOOK 640 G3.webp", 
            },
        { name: "HP Spectre", image: "images/sell-laptop-models/hp/HP SPECTRE X360.webp", 
            },
        { name: "HP Victus", image: "images/sell-laptop-models/hp/HP VICTUS.webp", 
            },
        { name: "HP ZBook Studio", image: "images/sell-laptop-models/hp/HP ZBOOK STUDIO.webp", 
            },         
    ],
    "ACER":[
        { name: "ACER Aspire 3", image: "images/sell-laptop-models/ACER/ACER ASPIRE 3.webp", 
        },
        { name: "ACER Aspire 5", image: "images/sell-laptop-models/ACER/Acer Aspire 5.webp", 
        },
        { name: "ACER Aspire 7", image: "images/sell-laptop-models/ACER/acer aspire 7.webp", 
        },
        { name: "ACER Aspire Lite", image: "images/sell-laptop-models/ACER/acer aspir lite.webp", 
        },
        { name: "ACER Extensa", image: "images/sell-laptop-models/ACER/Acer Extensa.webp", 
        },
        { name: "ACER Nitro V", image: "images/sell-laptop-models/ACER/Acer Nitro V.webp", 
        },
        { name: "ACER ONE", image: "images/sell-laptop-models/ACER/ACER ONE.webp", 
        },
        { name: "ACER Predator Helios Neo ", image: "images/sell-laptop-models/ACER/Acer Predator Helios Neo 16.webp", 
        },
        { name: "ACER Swift Go 14 SNAPDRAGON X Plus", image: "images/sell-laptop-models/ACER/ACER SWIFT GO 14 SNAPDRAGON X PLUS.webp", 
        },
        { name: "ACER Swift Go 14 Touch Screen", image: "images/sell-laptop-models/ACER/ACER SWIFT GO 14 TOUCH SCREEN.webp", 
        },
        { name: "ACER Travelmate", image: "images/sell-laptop-models/ACER/Acer Travelmate.webp", 
        },
    ],
    "ASUS":[
        { name: "ASUS ChromeBook", image: "images/sell-laptop-models/ASUS/ASUS CHROMEBOOK.webp", 
        },
        { name: "ASUS ExpertBook B14", image: "images/sell-laptop-models/ASUS/ASUS EXPERTBOOK B14.webp", 
        },
        { name: "ASUS ROG Strix G16", image: "images/sell-laptop-models/ASUS/ASUS ROG STRIX G16.webp", 
        },
        { name: "ASUS TUF Gaming A15", image: "images/sell-laptop-models/ASUS/ASUS TUF GAMING A15.webp", 
        },
        { name: "ASUS TUF Gaming F15", image: "images/sell-laptop-models/ASUS/ASUS TUF GAMING F15.webp", 
        },
        { name: "ASUS TUF Gaming F17", image: "images/sell-laptop-models/ASUS/ASUS TUF GAMING F17.webp", 
        },
        { name: "ASUS VivoBook 15", image: "images/sell-laptop-models/ASUS/ASUS VIVO BOOK 15.webp", 
        },
        { name: "ASUS VivoBook 16X", image: "images/sell-laptop-models/ASUS/ASUS VIVO BOOK 16X.webp", 
        },
        { name: "ASUS VivoBook 15 GO", image: "images/sell-laptop-models/ASUS/ASUS VIVOBOOK 15 GO.webp", 
        },
        { name: "ASUS VivoBook 15 Go OLED", image: "images/sell-laptop-models/ASUS/ASUS VIVOBOOK GO 15 OLED.webp", 
        },
        { name: "ASUS ZenBook S14", image: "images/sell-laptop-models/ASUS/ASUS Zenbook S14.webp", 
        },

    ],
    "DELL":[
        { name: "DELL 15", image: "images/sell-laptop-models/dell/DELL 15.webp", 
        },
        { name: "DELL Insipiron 7741 Plus", image: "images/sell-laptop-models/dell/DELL INSIPIRON 7741 PLUS.webp", 
        },
        { name: "DELL Intel Celeron Dual Core", image: "images/sell-laptop-models/dell/DELL INTEL CELERON DUAL CORE.webp", 
        },
        { name: "DELL Intel Core", image: "images/sell-laptop-models/dell/DELL INTEL CORE.webp", 
        },
        { name: "DELL Latitude 3440", image: "images/sell-laptop-models/dell/DELL LATITUDE 3440.webp", 
        },
        { name: "DELL MSO'2021", image: "images/sell-laptop-models/dell/DELL MSO'2021.webp", 
        },
        { name: "DELL Vostro 15 3520", image: "images/sell-laptop-models/dell/DELL VOSTRO 15 3520 LAPTOP.webp", 
        },
        { name: "DELL G15-5530", image: "images/sell-laptop-models/dell/dell{smartchoice}G15-5530.webp", 
        },

    ],
    "LENOVO":[
        { name: "Lenovo ChromeBook", image: "images/sell-laptop-models/Lenovo/Lenovo Chromebook.webp", 
        },
        { name: "Lenovo IdeaPad 3", image: "images/sell-laptop-models/Lenovo/Lenovo IdeaPad 3.webp", 
        },
        { name: "Lenovo IdeaPad Flex 5", image: "images/sell-laptop-models/Lenovo/Lenovo IdeaPad Flex 5.webp", 
        },
        { name: "Lenovo IdeaPad pro 5", image: "images/sell-laptop-models/Lenovo/Lenovo IdeaPad pro 5.webp", 
        },
        { name: "Lenovo IdeaPad Slim 1", image: "images/sell-laptop-models/Lenovo/Lenovo IdeaPad Slim 1.webp", 
        },
        { name: "Lenovo IdeaPad Slim 5", image: "images/sell-laptop-models/Lenovo/Lenovo IdeaPad Slim 5.webp", 
        },
        { name: "Lenovo Legion 5", image: "images/sell-laptop-models/Lenovo/Lenovo Legion 5.webp", 
        },
        { name: "Lenovo LOQ", image: "images/sell-laptop-models/Lenovo/Lenovo LOQ.webp", 
        },
        { name: "Lenovo ThinkPad E14", image: "images/sell-laptop-models/Lenovo/Lenovo Thinkpad E14.webp", 
        },
        { name: "Lenovo V14", image: "images/sell-laptop-models/Lenovo/Lenovo V14.webp", 
        },
        { name: "Lenovo V15 G3 IAP", image: "images/sell-laptop-models/Lenovo/Lenovo V15 G3 IAP.webp", 
        },
        { name: "Lenovo Yoga Slim 6", image: "images/sell-laptop-models/Lenovo/Lenovo Yoga Slim 6 WUXGA.webp", 
        },
        { name: "Lenovo Yoga Slim 7", image: "images/sell-laptop-models/Lenovo/Lenovo Yoga Slim 7.webp", 
        },


    ],
    "MICROSOFT":[
        { name: "MICROSOFT Laptop Go 3", image: "images/sell-laptop-models/microsoft/MICROSOFT Laptop Go 3.webp", 
        },
        { name: "MICROSOFT Surface Laptop 4", image: "images/sell-laptop-models/microsoft/MICROSOFT Surface Laptop 4.webp", 
        },
        { name: "MICROSOFT Surface Laptop 5", image: "images/sell-laptop-models/microsoft/MICROSOFT Surface Laptop 5.webp", 
        },
        { name: "MICROSOFT Surface Laptop", image: "images/sell-laptop-models/microsoft/MICROSOFT Surface Laptop.webp", 
        },
        { name: "MICROSOFT Surface Pro 7+", image: "images/sell-laptop-models/microsoft/MICROSOFT Surface Pro 7+.webp", 
        },
        { name: "MICROSOFT Surface Pro 8", image: "images/sell-laptop-models/microsoft/MICROSOFT Surface Pro 8.webp", 
        },
        { name: "MICROSOFT Surface Pro 9", image: "images/sell-laptop-models/microsoft/MICROSOFT Surface Pro 9.webp", 
        },
        

    ],
    "MSI":[
        { name: "MSI Bravo 15", image: "images/sell-laptop-models/MSI/MSI Bravo 15.webp", 
        },
        { name: "MSI Creator Z16", image: "images/sell-laptop-models/MSI/MSI Creator Z16.webp", 
        },
        { name: "MSI Crosshair 16HX", image: "images/sell-laptop-models/MSI/MSI Crosshair 16HX.webp", 
        },
        { name: "MSI Cyborg 15", image: "images/sell-laptop-models/MSI/MSI Cyborg 15.webp", 
        },
        { name: "MSI GF63 Thin", image: "images/sell-laptop-models/MSI/MSI GF63 Thin.webp", 
        },
        { name: "MSI GL Series", image: "images/sell-laptop-models/MSI/MSI GL Series.webp", 
        },
        { name: "MSI GP66 Leopard", image: "images/sell-laptop-models/MSI/MSI GP66 Leopard.webp", 
        },
        { name: "MSI Katana 15", image: "images/sell-laptop-models/MSI/MSI Katana 15.webp", 
        },
        { name: "MSI Katana A15", image: "images/sell-laptop-models/MSI/MSI Katana A15.webp", 
        },
        { name: "MSI Modern 14", image: "images/sell-laptop-models/MSI/MSI Modern 14.webp", 
        },
        { name: "MSI Modern 15H", image: "images/sell-laptop-models/MSI/MSI Modern 15H.webp", 
        },
        { name: "MSI Prestige 14", image: "images/sell-laptop-models/MSI/MSI Prestige 14.webp", 
        },
        { name: "MSI Pulse GL66", image: "images/sell-laptop-models/MSI/MSI Pulse GL66.webp", 
        },
        { name: "MSI Stealth 15", image: "images/sell-laptop-models/MSI/MSI Stealth 15.webp", 
        },
        { name: "MSI Summit E14 FlipEvo", image: "images/sell-laptop-models/MSI/MSI Summit E14 FlipEvo.webp", 
        },
        { name: "MSI Sword 16 HX", image: "images/sell-laptop-models/MSI/MSI Sword 16 HX.webp", 
        },
        { name: "MSI Thin 15", image: "images/sell-laptop-models/MSI/MSI Thin 15.webp", 
        },
        { name: "MSI Titan GT77", image: "images/sell-laptop-models/MSI/MSI Titan GT77.webp", 
        },
        { name: "MSI Vector GP78HX", image: "images/sell-laptop-models/MSI/MSI Vector GP78HX.webp", 
        },

    ],
    "APPLE": [
    { name: "2022 APPLE MAC BOOK AIR", image: "images/sell-laptop-models/apple/2022 APPLE MAC BOOK AIR.webp" },
    { name: "Apple 2020 MacBook Air Apple M1", image: "images/sell-laptop-models/apple/Apple 2020 MacBook Air Apple M1.webp" },
    { name: "Apple 2024 MacBook Air 15", image: "images/sell-laptop-models/apple/Apple 2024 MacBook Air 15.webp" },
    { name: "APPLE Apple M3", image: "images/sell-laptop-models/apple/APPLE Apple M3.webp" },
    { name: "Apple MacBook Air Apple M2", image: "images/sell-laptop-models/apple/Apple MacBook Air Apple M2.webp" },
    { name: "Apple MacBook Air Apple M3", image: "images/sell-laptop-models/apple/Apple MacBook Air Apple M3.webp" },
    { name: "Apple MacBook Pro Apple M3 Pro", image: "images/sell-laptop-models/apple/Apple MacBook Pro Apple M3 Pro.webp" }
],

};
